from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class PreprocessRequest(BaseModel):
    image_base64: str = Field(..., description="Base64 encoded scan image")
    apply_thinning: bool = Field(default=True, description="Enable Zhang-Suen stroke thinning")
    auto_deskew: bool = Field(default=True, description="Perform Hough line angle deskewing")

class PreprocessResponse(BaseModel):
    processed_image_base64: str
    skew_angle_deg: float
    dpi_detected: int
    contrast_ratio: float
    stroke_width_px: float

class KeyConceptRubric(BaseModel):
    concept: str
    weight_marks: float
    synonyms: List[str] = []
    description: Optional[str] = None

class QuestionRubric(BaseModel):
    question_number: int
    question_text: str
    max_marks: float
    model_answer: str
    key_concepts: List[KeyConceptRubric] = []
    leniency_threshold_pct: Optional[float] = 80.0

class StudentAnswerItem(BaseModel):
    question_number: int
    student_answer_text: str

class PageOcrResult(BaseModel):
    page_number: int
    text: str
    confidence: float = 0.95
    word_count: int = 0
    lines: List[DetectedLine] = []
    detected_answers: List[ParsedAnswerItem] = []
    preprocessed: bool = False
    skew_angle_deg: Optional[float] = 0.0
    status: str = "SUCCESS"
    error_message: Optional[str] = None

class OcrParseRequest(BaseModel):
    image_base64: Optional[str] = None
    pages: Optional[List[str]] = None
    preprocess: bool = True
    auto_deskew: bool = True
    apply_thinning: bool = False
    questions: Optional[List[QuestionRubric]] = None
    document_name: Optional[str] = None

class OcrParseResponse(BaseModel):
    raw_transcription: str
    extracted_text: Optional[str] = None
    detected_answers: List[ParsedAnswerItem] = []
    detected_lines: List[DetectedLine] = []
    pages: List[PageOcrResult] = []
    total_pages: int = 1
    successful_pages: int = 1
    total_words_detected: int = 0
    avg_confidence: float = 0.95
    status: str = "SUCCESS"
    error_message: Optional[str] = None

DocumentOcrRequest = OcrParseRequest
DocumentOcrResponse = OcrParseResponse

class EvaluationRequest(BaseModel):
    questions: List[QuestionRubric]
    student_answers: List[StudentAnswerItem]
    student_name: Optional[str] = "Candidate"

class ConceptMatchResult(BaseModel):
    concept: str
    awarded_marks: float
    max_marks: float
    matched_phrases: List[str]
    is_satisfied: bool

class QuestionEvaluationResult(BaseModel):
    question_number: int
    question_text: Optional[str] = None
    student_answer_text: str
    model_answer_text: str
    max_marks: float
    suggested_marks: float
    awarded_marks: float
    semantic_similarity_score: float
    concept_matches: List[ConceptMatchResult]
    feedback: str
    strengths: List[str]
    improvements: List[str]
    confidence: float = 0.95
    confidence_score: float = 0.95
    is_suggestion: bool = True

class EvaluationResponse(BaseModel):
    student_name: str
    suggested_total_marks: float
    total_score: float
    max_score: float
    percentage: float
    grade: str
    confidence: float = 0.95
    is_suggestion: bool = True
    status: str = "PENDING_TEACHER_REVIEW"
    disclaimer: str = "This evaluation is generated by AI as a recommendation. Final marks must be reviewed and finalized by the instructor."
    question_evaluations: List[QuestionEvaluationResult]
    overall_summary: str
    key_strengths: List[str]
    priority_improvements: List[str]
    blooms_taxonomy_level: str
